### ISSUE TITLE
How to route all traffic to a specified tun device by using this library? 

### ISSUE THREAD

**Issue by xmh0511** [johnyburd/net-route#8] opened 2023-12-07 03:59 UTC
How do I achieve this target by using this crate? Honestly, the documentation is lack, I don't know how to do.

**Comment by johnyburd** [comment] 2024-01-11 05:47
You might first want to determine the ifindex since the library doesn't currently support specifying interfaces by name #7, for example with this function: https://www.man7.org/linux/man-pages/man3/if_nametoindex.3.html

```rs
let tun_ifindex: u32 = 3;

let handle = Handle::new()?;
let route = Route::new("0.0.0.0".parse().unwrap(), 0).with_ifindex(tun_ifindex);
handle.add(&route).await
 ```

**Comment by xmh0511** [comment] 2024-01-12 01:55
> You might first want to determine the ifindex since the library doesn't currently support specifying interfaces by name #7, for example with this function: https://www.man7.org/linux/man-pages/man3/if_nametoindex.3.html
> 
> ```rust
> let tun_ifindex: u32 = 3;
> 
> let handle = Handle::new()?;
> let route = Route::new("0.0.0.0".parse().unwrap(), 0).with_ifindex(tun_ifindex);
> handle.add(&route).await
> ```

Thanks. But, what should I do on the Windows platform? IMO, Windows does not have an interface index.

**Comment by xmh0511** [comment] 2024-01-12 05:41
@johnyburd `handle.add(&route).await` just return the error:
> Err(Custom { kind: AlreadyExists, error: "rtm_errno 17" })

**Comment by johnyburd** [comment] 2024-01-12 21:21
yes [`Route::with_ifindex`](https://docs.rs/net-route/latest/x86_64-pc-windows-msvc/net_route/struct.Route.html#method.with_ifindex) is supported on windows.

I'm not able to tell what's wrong in the snipped you posted from macos. I would need a minimum reproduction of the error and perhaps a dump of your routing table.

**Comment by xmh0511** [comment] 2024-01-15 03:16
> yes [`Route::with_ifindex`](https://docs.rs/net-route/latest/x86_64-pc-windows-msvc/net_route/struct.Route.html#method.with_ifindex) is supported on windows.
> 
> I'm not able to tell what's wrong in the snipped you posted from macos. I would need a minimum reproduction of the error and perhaps a dump of your routing table.

It's here https://github.com/johnyburd/net-route/issues/15#issuecomment-1890300339

**Comment by johnyburd** [comment] 2024-02-23 04:56
Closing in favor of #7

**Closed by johnyburd** 2024-02-23 04:56 UTC
